openapi: 3.0.0
info:
  description: |

  license:
    name: Apache 2.0
  title: Financial Statements
  version: 1.0.0-RC

paths:
  /companies/{companyId}/financial-statements:
    get:
      tags:
        - Financial Statements
      summary: Get Financial Statements
      operationId: GetFinancialStatements
      parameters:
        - name: companyId
          in: path
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetFinancialStatementsResponse'
    post:
      tags:
        - Financial Statements
      summary: Create Financial Statements
      operationId: CreateFinancialStatements
      parameters:
        - name: companyId
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFinancialStatementsRequest'
      responses:
        201:
          description: Ok
    delete:
      tags:
        - Financial Statements
      summary: Delete Financial Statements
      operationId: DeleteFinancialStatements
      parameters:
        - name: companyId
          in: path
          schema:
            type: string
      responses:
        202:
          description: Accepted
  /companies/{companyId}/financial-statements/{id}:
    get:
      summary: Get Financial Statement
      operationId: GetFinancialStatement
      parameters:
        - name: companyId
          in: path
          schema:
            type: string
        - name: id
          in: path
          schema:
            type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GaapFinancialStatement'
    delete:
      summary: Delete Financial Statement
      operationId: DeleteFinancialStatement
      parameters:
        - name: companyId
          in: path
          schema:
            type: string
        - name: id
          in: path
          schema:
            type: string
      responses:
        202:
          description: Accepted
    put:
      summary: Update Financial Statement
      operationId: UpdateFinancialStatement
      parameters:
        - name: companyId
          in: path
          schema:
            type: string
        - name: id
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GaapFinancialStatement'
      responses:
        202:
          description: Accepted


  /companies/financial-statements/_search:
    post:
      summary: Search Financial Statements
      operationId: SearchFinancialStatements
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchFinancialStatementsRequest'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchFinancialStatementsResponse'


components:
  schemas:
    GaapFinancialStatement:
      properties:
        companyId:
          type: string
        id:
          type: string
          format: uuid
          example: 9ce6ead2-7f2c-4165-915d-fdb5d179fb25
        filingType:
          type: string
          enum:
            - 10K
            - 10Q
        url:
          type: string
        date:
          type: string
          format: date
          example: 2018-09-29
        createdOn:
          type: string
          format: 'date-time'
        createdBy:
          type: string
        updatedOn:
          type: string
          format: 'date-time'
        updatedBy:
          type: string
        incomeStatement:
          $ref: '#/components/schemas/IncomeStatement'
        balanaceSheet:
          $ref: '#/components/schemas/BalanceSheet'
        cashflowStatement:
          $ref: '#/components/schemas/CashflowStatement'
    IncomeStatement:
      properties:
        totalRevenue:
          type: number
          format: double
        costOfRevenue:
          type: number
          format: double
        grossProfit:
          type: number
          format: double
        researchDevelopment:
          type: number
          format: double
        sellingGeneralAndAdministrative:
          type: number
          format: double
        totalOperatingExpenses:
          type: number
          format: double
        operatingIncomeOrLoss:
          type: number
          format: double
        totalOtherIncomeOrExpensesNet:
          type: number
          format: double
        earningsBeforeInterestAndTaxes:
          type: number
          format: double
        interestExpense:
          type: number
          format: double
        incomeBeforeTax:
          type: number
          format: double
        incomeTaxExpense:
          type: number
          format: double
        netIncomeFromContinuingOps:
          type: number
          format: double
        netIncome:
          type: number
          format: double
        netIncomeApplicableToCommonShares:
          type: number
          format: double
    BalanceSheet:
      properties:
        cashAndCashEquivalents:
          type: number
          format: double
        shortTermInvestments:
          type: number
          format: double
        netReceivables:
          type: number
          format: double
        inventory:
          type: number
          format: double
        otherCurrentAssets:
          type: number
          format: double
        totalCurrentAssets:
          type: number
          format: double
        longTermInvestments:
          type: number
          format: double
        propertyPlantAndEquipment:
          type: number
          format: double
        otherAssets:
          type: number
          format: double
        totalAssets:
          type: number
          format: double
        accountsPayable:
          type: number
          format: double
        shortOrCurrentLongTermDebt:
          type: number
          format: double
        otherCurrentLiabilities:
          type: number
          format: double
        totalCurrentLiabilities:
          type: number
          format: double
        longTermDebt:
          type: number
          format: double
        otherLiabilities:
          type: number
          format: double
        totalLiabilities:
          type: number
          format: double
        commonStock:
          type: number
          format: double
        retainedEarnings:
          type: number
          format: double
        treasuryStock:
          type: number
          format: double
        otherStockholderEquity:
          type: number
          format: double
        totalStockholderEquity:
          type: number
          format: double
        netTangibleAssets:
          type: number
          format: double
    CashflowStatement:
      properties:
        netIncome:
          type: number
          format: double
        depreciation:
          type: number
          format: double
        adjustmentsToNetIncome:
          type: number
          format: double
        changesInAccountsReceivables:
          type: number
          format: double
        changesInLiabilities:
          type: number
          format: double
        changesInInventories:
          type: number
          format: double
        changesInOtherOperatingActivities:
          type: number
          format: double
        totalCashFlowFromOperatingActivities:
          type: number
          format: double
        capitalExpenditures:
          type: number
          format: double
        investments:
          type: number
          format: double
        otherCashFlowsFromInvestingActivities:
          type: number
          format: double
        totalCashFlowsFromInvestingActivities:
          type: number
          format: double
        dividendsPaid:
          type: number
          format: double
        netBorrowings:
          type: number
          format: double
        totalCashFlowsFromFinancingActivities:
          type: number
          format: double
        changeInCashAndCashEquivalents:
          type: number
          format: double
    GetFinancialStatementsResponse:
      properties:
        financialStatements:
          type: array
          items:
            $ref: '#/components/schemas/GaapFinancialStatement'
    CreateFinancialStatementsRequest:
      properties:
        financialStatements:
          type: array
          items:
            $ref: '#/components/schemas/GaapFinancialStatement'
    SearchFinancialStatementsResponse:
      properties:
        financialStatements:
          type: array
          items:
            $ref: '#/components/schemas/GaapFinancialStatement'
    SearchFinancialStatementsRequest:
      properties:
        start:
          type: string
          format: date
        end:
          type: string
          format: date
        filingType:
          type: string
          enum:
            - 10K
            - 10Q
        companyId:
          type: string